declare module '@strapi/icons'

declare module '@strapi/icons/ArrowRight'
declare module '@strapi/icons/Check'
declare module '@strapi/icons/CheckCircle'
declare module '@strapi/icons/Cross'
declare module '@strapi/icons/Duplicate'
declare module '@strapi/icons/ExclamationMarkCircle'
declare module '@strapi/icons/Information'
declare module '@strapi/icons/Plus'
declare module '@strapi/icons/Trash'
declare module '@strapi/icons/Pencil'
declare module '@strapi/icons/CloudUpload'
declare module '@strapi/icons/Link'
